from typing import Dict

YOLO_WASTE_CATEGORY_MAP: Dict[str, str] = {
    "bottle": "plástico",
    "cup": "plástico",
    "wine glass": "vidro",
    "bowl": "plástico",
    "fork": "metal",
    "knife": "metal",
    "spoon": "metal",
    "banana": "orgânico",
    "apple": "orgânico",
    "orange": "orgânico",
    "broccoli": "orgânico",
    "carrot": "orgânico",
    "sandwich": "orgânico",
    "pizza": "orgânico",
    "hot dog": "orgânico",
    "donut": "orgânico",
    "cake": "orgânico",
    "cell phone": "eletrônico",
    "tv": "eletrônico",
    "laptop": "eletrônico",
    "mouse": "eletrônico",
    "remote": "eletrônico",
    "keyboard": "eletrônico",
    "book": "papel",
    "cardboard": "papel",
    "truck": "veículo/coleta",
    "car": "veículo",
    "motorcycle": "veículo",
    "bus": "veículo/coleta",
    "person": "não resíduo",
    "dog": "não resíduo",
    "cat": "não resíduo",
    "chair": "entulho",
    "couch": "entulho",
    "bed": "entulho",
    "dining table": "entulho",
    "toilet": "entulho",
    "potted plant": "orgânico",
    "backpack": "descarte misto",
    "handbag": "descarte misto",
    "suitcase": "descarte misto",
    "tie": "descarte misto",
    "umbrella": "descarte misto"
}

def map_yolo_class_to_waste_category(class_name: str) -> str:
    return YOLO_WASTE_CATEGORY_MAP.get(class_name.lower(), "descarte misto")